/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./../components/ui/BaseModal.vue')['default']
    ConfigPanel: typeof import('./../components/ConfigPanel.vue')['default']
    DataTable: typeof import('./../components/ui/DataTable.vue')['default']
    DefenseManagementModal: typeof import('./../components/modals/DefenseManagementModal.vue')['default']
    FormField: typeof import('./../components/ui/FormField.vue')['default']
    LoginModal: typeof import('./../components/modals/LoginModal.vue')['default']
    LogTable: typeof import('./../components/LogTable.vue')['default']
    MapChart: typeof import('./../components/MapChart.vue')['default']
    NavItem: typeof import('./../components/ui/NavItem.vue')['default']
    PathList: typeof import('./../components/PathList.vue')['default']
    PolicyEditModal: typeof import('./../components/modals/PolicyEditModal.vue')['default']
    PrimaryButton: typeof import('./../components/ui/PrimaryButton.vue')['default']
    RegionList: typeof import('./../components/RegionList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityConsoleModal: typeof import('./../components/modals/SecurityConsoleModal.vue')['default']
    SettingRow: typeof import('./../components/ui/SettingRow.vue')['default']
    StatusPing: typeof import('./../components/ui/StatusPing.vue')['default']
    SystemSettingsModal: typeof import('./../components/modals/SystemSettingsModal.vue')['default']
    TagInput: typeof import('./../components/ui/TagInput.vue')['default']
    TheHeader: typeof import('./../components/layout/TheHeader.vue')['default']
    ToggleSwitch: typeof import('./../components/ui/ToggleSwitch.vue')['default']
    UserProfileDropdown: typeof import('./../components/layout/UserProfileDropdown.vue')['default']
  }
}
