import { ref, computed } from 'vue';

import * as fabricLib from 'fabric';
const fabric = (fabricLib as any).fabric || (fabricLib as any).default || fabricLib;
import type { Ref } from 'vue';

import { useHistoryStore } from '@/stores/editor';

/**
 * 撤销/重做历史管理
 */
export function useHistory(
  fCanvas: Ref<any>,
  isStateSavingLocked: { value: boolean },
  inkCanvas: HTMLCanvasElement | null,
  inkCtx: CanvasRenderingContext2D | null
) {
  const historyStore = useHistoryStore();
  const undoStack = computed({
    get: () => historyStore.undoStack,
    set: val => {
      historyStore.undoStack = val;
    }
  });
  const redoStack = computed({
    get: () => historyStore.redoStack,
    set: val => {
      historyStore.redoStack = val;
    }
  });
  let onStateRestored: (() => void) | null = null;
  let onReapplyTool: (() => void) | null = null;

  /** 设置状态恢复后的回调 */
  const setOnStateRestored = (cb: () => void) => {
    onStateRestored = cb;
  };
  /** 设置重新应用工具的回调 */
  const setOnReapplyTool = (cb: () => void) => {
    onReapplyTool = cb;
  };

  /** 保存当前状态到撤销栈 */
  const saveState = () => {
    if (isStateSavingLocked.value || !fCanvas.value) return;
    const json = fCanvas.value.toJSON([
      'id',
      'selectable',
      'evented',
      'hasControls',
      'hasBorders',
      'strokeWidth',
      'stroke',
      'fill',
      'radius',
      'scaleX',
      'scaleY',
      'originX',
      'originY',
      'name',
      'opacity',
      'isInkLayer',
      'isAutoGenerated',
      'isSkeleton',
      'connectedLines',
      'isUserStroke',
      'erasable',
      'isGuide',
      'guideType'
    ]);
    const snapshot = { fabric: json, ink: inkCanvas?.toDataURL() };
    const last = undoStack.value[undoStack.value.length - 1];
    if (last && JSON.stringify(snapshot) === JSON.stringify(last)) return;
    undoStack.value.push(snapshot);
    if (undoStack.value.length > 500) undoStack.value.shift();
    redoStack.value = [];
  };

  /** 从快照恢复状态 */
  const restoreState = (snapshot: any) => {
    if (!snapshot || !snapshot.fabric || !fCanvas.value) return;
    isStateSavingLocked.value = true;
    const p = new Promise(resolve => {
      if (!snapshot.ink) return resolve(null);
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
      img.src = snapshot.ink;
    });
    const safetyTimeout = setTimeout(() => {
      if (isStateSavingLocked.value) {
        isStateSavingLocked.value = false;
        console.warn('[History] State restoration safety timeout triggered (unlocked state saving)');
      }
    }, 1500);

    fCanvas.value.loadFromJSON(snapshot.fabric, async () => {
      clearTimeout(safetyTimeout);
      const img = await p;
      if (img && inkCtx && inkCanvas) {
        inkCtx.save();
        inkCtx.globalCompositeOperation = 'copy';
        inkCtx.drawImage(img as HTMLImageElement, 0, 0);
        inkCtx.restore();
      }
      const inkLayer = fCanvas.value.getObjects().find((o: any) => o.isInkLayer);
      if (inkLayer && inkCanvas) inkLayer.setElement(inkCanvas);

      // Restore active canvas element for stroke images so the eraser context is retrievable
      fCanvas.value.getObjects().forEach((o: any) => {
        if (o.isUserStroke && o.getElement) {
          const el = o.getElement();
          if (el && el.tagName === 'IMG') {
            const canvas = document.createElement('canvas');
            canvas.width = el.naturalWidth || el.width;
            canvas.height = el.naturalHeight || el.height;
            const ctx = canvas.getContext('2d');
            if (ctx) {
              ctx.drawImage(el, 0, 0);
              o.setElement(canvas);
            }
          }
        }
      });

      fCanvas.value.renderAll();
      isStateSavingLocked.value = false;
      // 通知外部状态已恢复
      if (onStateRestored) onStateRestored();
      // 重新应用当前工具的设置
      if (onReapplyTool) onReapplyTool();
    });
  };

  /** 撤销 */
  const undo = () => {
    if (undoStack.value.length <= 1) return;
    const c = undoStack.value.pop();
    redoStack.value.push(c);
    restoreState(undoStack.value[undoStack.value.length - 1]);
  };

  /** 重做 */
  const redo = () => {
    if (!redoStack.value.length) return;
    const n = redoStack.value.pop();
    undoStack.value.push(n);
    restoreState(n);
  };

  return { undoStack, redoStack, saveState, restoreState, undo, redo, setOnStateRestored, setOnReapplyTool };
}
