import { ref } from 'vue'
import type { Ref } from 'vue'

/**
 * 撤销/重做历史管理
 */
export function useHistory(fCanvas: Ref<any>, isStateSavingLocked: { value: boolean }, inkCanvas: HTMLCanvasElement | null, inkCtx: CanvasRenderingContext2D | null) {
  const undoStack = ref<any[]>([])
  const redoStack = ref<any[]>([])

  /** 保存当前状态到撤销栈 */
  const saveState = () => {
    if (isStateSavingLocked.value || !fCanvas.value) return
    const json = fCanvas.value.toJSON(['id', 'selectable', 'evented', 'hasControls', 'hasBorders', 'strokeWidth', 'stroke', 'fill', 'radius', 'scaleX', 'scaleY', 'originX', 'originY', 'name', 'opacity', 'isInkLayer', 'isAutoGenerated', 'isSkeleton', 'connectedLines'])
    const snapshot = { fabric: json, ink: inkCanvas?.toDataURL() }
    const last = undoStack.value[undoStack.value.length - 1]
    if (last && JSON.stringify(snapshot) === JSON.stringify(last)) return
    undoStack.value.push(snapshot)
    if (undoStack.value.length > 50) undoStack.value.shift()
    redoStack.value = []
  }

  /** 从快照恢复状态 */
  const restoreState = (snapshot: any) => {
    if (!snapshot || !snapshot.fabric || !fCanvas.value) return
    isStateSavingLocked.value = true
    const p = new Promise((resolve) => {
      if (!snapshot.ink) return resolve(null)
      const img = new Image()
      img.onload = () => resolve(img)
      img.onerror = () => resolve(null)
      img.src = snapshot.ink
    })
    fCanvas.value.loadFromJSON(snapshot.fabric, async () => {
      const img = await p
      if (img && inkCtx && inkCanvas) {
        inkCtx.save()
        inkCtx.globalCompositeOperation = 'copy'
        inkCtx.drawImage(img, 0, 0)
        inkCtx.restore()
      }
      const inkLayer = fCanvas.value.getObjects().find((o: any) => o.isInkLayer)
      if (inkLayer && inkCanvas) inkLayer.setElement(inkCanvas)
      fCanvas.value.renderAll()
      isStateSavingLocked.value = false
    })
  }

  /** 撤销 */
  const undo = () => {
    if (undoStack.value.length <= 1) return
    const c = undoStack.value.pop()
    redoStack.value.push(c)
    restoreState(undoStack.value[undoStack.value.length - 1])
  }

  /** 重做 */
  const redo = () => {
    if (!redoStack.value.length) return
    const n = redoStack.value.pop()
    undoStack.value.push(n)
    restoreState(n)
  }

  return { undoStack, redoStack, saveState, restoreState, undo, redo }
}
