import { ref } from 'vue'
import type { Ref } from 'vue'
import * as fabric from 'fabric'
import { v4 as uuidv4 } from 'uuid'

/**
 * 骨架节点管理
 */
export function useSkeletonNodes(fCanvas: Ref<any>, currentColor: Ref<string>, saveState: () => void) {

  /** 映射关键点坐标 */
  const mapPoint = (k: any, offset: any) => {
    if (offset) return { x: offset.x + k.x * offset.sw, y: offset.y + k.y * offset.sh }
    const bg = fCanvas.value?.backgroundImage
    if (!bg) return { x: k.x, y: k.y }
    return {
      x: bg.left - bg.getScaledWidth() / 2 + k.x * bg.scaleX,
      y: bg.top - bg.getScaledHeight() / 2 + k.y * bg.scaleY
    }
  }

  /** 绘制姿势骨架 */
  const drawPoseSkeleton = (pose: any, offset: any = null) => {
    if (!fCanvas.value) return
    const fp = ['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear']
    const kp: any = {}
    pose.keypoints.forEach((k: any) => {
      if (k.score > 0.2 && !fp.includes(k.name)) kp[k.name] = mapPoint(k, offset)
    })
    const edges = [
      ['left_shoulder', 'right_shoulder'], ['left_shoulder', 'left_elbow'], ['right_shoulder', 'right_elbow'],
      ['left_elbow', 'left_wrist'], ['right_elbow', 'right_wrist'], ['left_shoulder', 'left_hip'],
      ['right_shoulder', 'right_hip'], ['left_hip', 'right_hip'], ['left_hip', 'left_knee'],
      ['right_hip', 'right_knee'], ['left_knee', 'left_ankle'], ['right_knee', 'right_ankle']
    ]
    const nm: any = {}
    Object.entries(kp).forEach(([name, p]: [string, any]) => {
      const c = new fabric.Circle({
        id: uuidv4(), left: p.x, top: p.y, radius: 8,
        fill: '#ffffff', stroke: currentColor.value, strokeWidth: 3,
        originX: 'center', originY: 'center',
        selectable: true, evented: true, isSkeleton: true,
        padding: 12, name, erasable: true
      })
      c.connectedLines = []; nm[name] = c
      fCanvas.value.add(c); c.setCoords()
    })
    edges.forEach(([a, b]) => {
      if (!nm[a] || !nm[b]) return
      const nA = nm[a], nB = nm[b], id = uuidv4()
      const l = new fabric.Line([nA.left, nA.top, nB.left, nB.top], {
        id, stroke: currentColor.value, strokeWidth: 3,
        selectable: true, evented: true, isAutoGenerated: true,
        strokeLineCap: 'round', opacity: 0.8, erasable: true
      })
      nA.connectedLines.push({ line: id, endpoint: 'start' })
      nB.connectedLines.push({ line: id, endpoint: 'end' })
      fCanvas.value.add(l); l.sendToBack()
    })
    Object.values(nm).forEach((c: any) => c.bringToFront())
  }

  /** 添加新骨架节点 */
  const addSkeletonNode = (x: number, y: number) => {
    if (!fCanvas.value) return
    const id = uuidv4()
    const node = new fabric.Circle({
      id, left: x, top: y, radius: 8,
      fill: '#ffffff', stroke: currentColor.value, strokeWidth: 3,
      originX: 'center', originY: 'center',
      selectable: true, evented: true, isSkeleton: true,
      padding: 12, name: `node_${Date.now()}`, erasable: true
    })
    node.connectedLines = []
    fCanvas.value.add(node)
    node.bringToFront()
    fCanvas.value.setActiveObject(node)
    fCanvas.value.renderAll()
    saveState()
  }

  /** 在节点连接的线段中点添加新节点 */
  const addMidpointNode = (node: any) => {
    if (!fCanvas.value || !node.connectedLines?.length) return
    const objs = fCanvas.value.getObjects()
    const idMap: any = {}
    objs.forEach((o: any) => { if (o.id) idMap[o.id] = o })

    const conn = node.connectedLines[0]
    const line = idMap[conn.line || conn.id]
    if (!line) return

    const mx = (line.x1 + line.x2) / 2
    const my = (line.y1 + line.y2) / 2

    const id = uuidv4()
    const newNode = new fabric.Circle({
      id, left: mx, top: my, radius: 8,
      fill: '#ffffff', stroke: currentColor.value, strokeWidth: 3,
      originX: 'center', originY: 'center',
      selectable: true, evented: true, isSkeleton: true,
      padding: 12, name: `node_${Date.now()}`, erasable: true
    })
    newNode.connectedLines = []

    const otherEndpoint = conn.endpoint === 'start' ? 'end' : 'start'
    const otherConn = objs.find((o: any) =>
      o.isSkeleton && o !== node && o.connectedLines?.some((c: any) =>
        (c.line || c.id) === (conn.line || conn.id) && c.endpoint === otherEndpoint
      )
    )

    node.connectedLines = node.connectedLines.filter((c: any) => (c.line || c.id) !== (conn.line || conn.id))
    fCanvas.value.remove(line)

    const line1Id = uuidv4()
    const line1 = new fabric.Line([node.left, node.top, mx, my], {
      id: line1Id, stroke: currentColor.value, strokeWidth: 3,
      selectable: true, evented: true, isAutoGenerated: true,
      strokeLineCap: 'round', opacity: 0.8, erasable: true
    })
    node.connectedLines.push({ line: line1Id, endpoint: 'start' })
    newNode.connectedLines.push({ line: line1Id, endpoint: 'end' })
    fCanvas.value.add(line1); line1.sendToBack()

    if (otherConn) {
      const line2Id = uuidv4()
      const line2 = new fabric.Line([mx, my, otherConn.left, otherConn.top], {
        id: line2Id, stroke: currentColor.value, strokeWidth: 3,
        selectable: true, evented: true, isAutoGenerated: true,
        strokeLineCap: 'round', opacity: 0.8, erasable: true
      })
      newNode.connectedLines.push({ line: line2Id, endpoint: 'start' })
      otherConn.connectedLines = otherConn.connectedLines.map((c: any) => {
        if ((c.line || c.id) === (conn.line || conn.id)) return { line: line2Id, endpoint: 'end' }
        return c
      })
      fCanvas.value.add(line2); line2.sendToBack()
    }

    fCanvas.value.add(newNode)
    newNode.bringToFront()
    fCanvas.value.setActiveObject(newNode)
    fCanvas.value.renderAll()
    saveState()
  }

  /** 连接两个骨架节点 */
  const connectNodes = (nodeA: any, nodeB: any) => {
    if (!fCanvas.value) return

    const existingConn = nodeA.connectedLines?.find((c: any) => {
      const objs = fCanvas.value.getObjects()
      const line = objs.find((o: any) => o.id === (c.line || c.id))
      if (!line) return false
      return objs.some((o: any) =>
        o.isSkeleton && o === nodeB &&
        o.connectedLines?.some((oc: any) => (oc.line || oc.id) === (c.line || c.id))
      )
    })
    if (existingConn) return

    const id = uuidv4()
    const line = new fabric.Line([nodeA.left, nodeA.top, nodeB.left, nodeB.top], {
      id, stroke: currentColor.value, strokeWidth: 3,
      selectable: true, evented: true, isAutoGenerated: true,
      strokeLineCap: 'round', opacity: 0.8, erasable: true
    })

    if (!nodeA.connectedLines) nodeA.connectedLines = []
    if (!nodeB.connectedLines) nodeB.connectedLines = []
    nodeA.connectedLines.push({ line: id, endpoint: 'start' })
    nodeB.connectedLines.push({ line: id, endpoint: 'end' })

    fCanvas.value.add(line); line.sendToBack()
    nodeA.bringToFront(); nodeB.bringToFront()
    fCanvas.value.renderAll()
    saveState()
  }

  return { mapPoint, drawPoseSkeleton, addSkeletonNode, addMidpointNode, connectNodes }
}
