import { ref, Ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { templateApi } from '@/api/template'
import { useUpload } from '@/composables/useUpload'

export function useTemplateSave(
  fCanvas: Ref<any>,
  templateName: Ref<string>,
  getInkCanvas: () => HTMLCanvasElement | null
) {
  const router = useRouter()
  const route = useRoute()
  const { uploadFile } = useUpload()

  const showSaveModal = ref(false)
  const showExitModal = ref(false)

  const saveTemplate = () => {
    showSaveModal.value = true
  }

  const triggerExit = () => {
    showExitModal.value = true
  }

  const goHome = () => {
    router.push('/')
  }

  const confirmSave = async (formData: {
    name: string
    description: string
    category: string
    locationName: string
    coords: { lat: number; lng: number } | null
    ip: string
    tags: string[]
    exifInfo?: any
  }) => {
    if (!fCanvas.value) return
    fCanvas.value.discardActiveObject()
    
    // 给渲染留出 100ms 呼吸时间，确保预览图不全为空白
    await new Promise(r => setTimeout(r, 100))
    // 辅助函数：将 Base64 转为 File 对象用于直传 FormData
    const dataURLtoFile = (dataurl: string, filename: string) => {
      const arr = dataurl.split(',')
      const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/jpeg'
      const bstr = atob(arr[1])
      let n = bstr.length
      const u8arr = new Uint8Array(n)
      while (n--) {
        u8arr[n] = bstr.charCodeAt(n)
      }
      return new File([u8arr], filename, { type: mime })
    }


    
    // 获取原始背景图(如果存在)
    let bgDataUrl = null
    const bgImage = fCanvas.value.backgroundImage
    if (bgImage) {
        if (bgImage.getSrc) {
            bgDataUrl = bgImage.getSrc()
        } else if (bgImage.toDataURL) {
            bgDataUrl = bgImage.toDataURL({ format: 'jpeg', quality: 0.8 })
        }
    }
    
    // 真实上传流程 (只上传原始背景图，预览图交由后端实时动态合成)
    let realBgUrl = ''
    
    try {
      if (bgDataUrl) {
         if (bgDataUrl.startsWith('data:')) {
            const bgFile = dataURLtoFile(bgDataUrl, `bg_${Date.now()}.jpg`)
            const bgUpload = await uploadFile(bgFile, 'posecraft')
            if (!bgUpload?.url) throw new Error('背景图上传失败')
            realBgUrl = bgUpload.url
         } else {
            realBgUrl = bgDataUrl
         }
      }
    } catch (e: any) {
      console.error('背景图片上传失败:', e)
      alert(e.message || '图片上传失败，请检查网络或图片尺寸')
      return // 强制阻断保存
    }
    
    const fabricJson = fCanvas.value.toJSON([
      'id', 'selectable', 'evented', 'connectedLines',
      'isSkeleton', 'isAutoGenerated', 'isGuide', 'isCropBox',
      'erasable', 'isUserStroke', 'isFace', 'isHand', 'isOutline'
    ])
    fabricJson.width = fCanvas.value.width
    fabricJson.height = fCanvas.value.height

    const inkCanvas = getInkCanvas()
    const templateData = {
      id: route.query.id || `posecraft_${Date.now()}`,
      name: formData.name || '未命名作品',
      description: formData.description || '',
      locationName: formData.locationName || '',
      coords: formData.coords,
      ip: formData.ip,
      tags: formData.tags,
      exifInfo: formData.exifInfo || null,
      thumb: realBgUrl,
      fabricData: fabricJson,
      inkData: inkCanvas?.toDataURL() || null,
      createdAt: new Date().toISOString()
    }

    try {
      const apiData = {
        title: formData.name || '未命名作品',
        description: formData.description || '',
        category: formData.category || 'pose',
        image_url: realBgUrl,
        pose_data: {
          fabricData: fabricJson,
          inkData: inkCanvas?.toDataURL() || null,
          locationName: formData.locationName || '',
          coords: formData.coords,
          exifInfo: formData.exifInfo || null
        },
        tags: formData.tags
      }
      
      const id = route.query.id ? Number(route.query.id) : null
      if (id) {
        await templateApi.update(id, apiData)
      } else {
        await templateApi.create(apiData)
      }

      alert('发布成功，已提交管理员审核！您和管理员可以随时查看您的作品。')
      showSaveModal.value = false
      goHome()
    } catch (err) {
      console.error('发布失败:', err)
      alert('保存失败，可能是图片上传过大或网络异常，请重试。')
    }
  }

  return {
    showSaveModal,
    showExitModal,
    saveTemplate,
    triggerExit,
    goHome,
    confirmSave
  }
}
