/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const captureAgreementVersion: typeof import('./composables/useAgreementVersion').captureAgreementVersion
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isConsentResponse: typeof import('./composables/useLoginFlow').isConsentResponse
  const isEmailVerifyResponse: typeof import('./composables/useLoginFlow').isEmailVerifyResponse
  const isLoginSuccessResponse: typeof import('./composables/useLoginFlow').isLoginSuccessResponse
  const isMaxSessionsResponse: typeof import('./composables/useLoginFlow').isMaxSessionsResponse
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const reportError: typeof import('./composables/useErrorReporter').reportError
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAgreementVersion: typeof import('./composables/useAgreementVersion').useAgreementVersion
  const useAntiCache: typeof import('./composables/useAntiCache').useAntiCache
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./stores/auth').useAuthStore
  const useButtonLock: typeof import('./composables/useButtonLock').useButtonLock
  const useCaptcha: typeof import('./composables/useCaptcha').useCaptcha
  const useCaptchaFlow: typeof import('./composables/useCaptchaFlow').useCaptchaFlow
  const useCountdown: typeof import('./composables/useCountdown').useCountdown
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDeviceDetect: typeof import('./composables/useDeviceDetect').useDeviceDetect
  const useHCaptcha: typeof import('./composables/useHCaptcha').useHCaptcha
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useKeyboardAvoid: typeof import('./composables/useKeyboardAvoid').useKeyboardAvoid
  const useLink: typeof import('vue-router').useLink
  const useLoginFlow: typeof import('./composables/useLoginFlow').useLoginFlow
  const useMessage: typeof import('./composables/useMessage').useMessage
  const useModel: typeof import('vue').useModel
  const useParentThemeSync: typeof import('./composables/useParentThemeSync').useParentThemeSync
  const usePasswordStrength: typeof import('./composables/usePasswordStrength').usePasswordStrength
  const useQrLogin: typeof import('./composables/useQrLogin').useQrLogin
  const useRecaptcha: typeof import('./composables/useHCaptcha').useRecaptcha
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSocialLogin: typeof import('./composables/useSocialLogin').useSocialLogin
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeStore: typeof import('./stores/theme').useThemeStore
  const useTurnstile: typeof import('./composables/useTurnstile').useTurnstile
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AgreementVersionSnapshot, UseAgreementVersionReturn } from './composables/useAgreementVersion'
  import('./composables/useAgreementVersion')
  // @ts-ignore
  export type { ButtonLockOptions } from './composables/useButtonLock'
  import('./composables/useButtonLock')
  // @ts-ignore
  export type { CaptchaInstance } from './composables/useCaptcha'
  import('./composables/useCaptcha')
  // @ts-ignore
  export type { CaptchaPurpose, CaptchaSuccessData } from './composables/useCaptchaFlow'
  import('./composables/useCaptchaFlow')
  // @ts-ignore
  export type { UseCountdownReturn } from './composables/useCountdown'
  import('./composables/useCountdown')
  // @ts-ignore
  export type { LoginResponse, LoginSuccessResponse, LoginUser, EmailVerifyState, UseLoginFlowOptions } from './composables/useLoginFlow'
  import('./composables/useLoginFlow')
  // @ts-ignore
  export type { PasswordLevel, PasswordStrength } from './composables/usePasswordStrength'
  import('./composables/usePasswordStrength')
  // @ts-ignore
  export type { QrStatus } from './composables/useQrLogin'
  import('./composables/useQrLogin')
  // @ts-ignore
  export type { SocialProviderId } from './composables/useSocialLogin'
  import('./composables/useSocialLogin')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly captureAgreementVersion: UnwrapRef<typeof import('./composables/useAgreementVersion')['captureAgreementVersion']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isConsentResponse: UnwrapRef<typeof import('./composables/useLoginFlow')['isConsentResponse']>
    readonly isEmailVerifyResponse: UnwrapRef<typeof import('./composables/useLoginFlow')['isEmailVerifyResponse']>
    readonly isLoginSuccessResponse: UnwrapRef<typeof import('./composables/useLoginFlow')['isLoginSuccessResponse']>
    readonly isMaxSessionsResponse: UnwrapRef<typeof import('./composables/useLoginFlow')['isMaxSessionsResponse']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly reportError: UnwrapRef<typeof import('./composables/useErrorReporter')['reportError']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAgreementVersion: UnwrapRef<typeof import('./composables/useAgreementVersion')['useAgreementVersion']>
    readonly useAntiCache: UnwrapRef<typeof import('./composables/useAntiCache')['useAntiCache']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('./stores/auth')['useAuthStore']>
    readonly useButtonLock: UnwrapRef<typeof import('./composables/useButtonLock')['useButtonLock']>
    readonly useCaptcha: UnwrapRef<typeof import('./composables/useCaptcha')['useCaptcha']>
    readonly useCaptchaFlow: UnwrapRef<typeof import('./composables/useCaptchaFlow')['useCaptchaFlow']>
    readonly useCountdown: UnwrapRef<typeof import('./composables/useCountdown')['useCountdown']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDeviceDetect: UnwrapRef<typeof import('./composables/useDeviceDetect')['useDeviceDetect']>
    readonly useHCaptcha: UnwrapRef<typeof import('./composables/useHCaptcha')['useHCaptcha']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useKeyboardAvoid: UnwrapRef<typeof import('./composables/useKeyboardAvoid')['useKeyboardAvoid']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLoginFlow: UnwrapRef<typeof import('./composables/useLoginFlow')['useLoginFlow']>
    readonly useMessage: UnwrapRef<typeof import('./composables/useMessage')['useMessage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useParentThemeSync: UnwrapRef<typeof import('./composables/useParentThemeSync')['useParentThemeSync']>
    readonly usePasswordStrength: UnwrapRef<typeof import('./composables/usePasswordStrength')['usePasswordStrength']>
    readonly useQrLogin: UnwrapRef<typeof import('./composables/useQrLogin')['useQrLogin']>
    readonly useRecaptcha: UnwrapRef<typeof import('./composables/useHCaptcha')['useRecaptcha']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSocialLogin: UnwrapRef<typeof import('./composables/useSocialLogin')['useSocialLogin']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemeStore: UnwrapRef<typeof import('./stores/theme')['useThemeStore']>
    readonly useTurnstile: UnwrapRef<typeof import('./composables/useTurnstile')['useTurnstile']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}