/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthContainer: typeof import('./components/common/AuthContainer.vue')['default']
    GraphicCaptcha: typeof import('./components/common/GraphicCaptcha.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icons: typeof import('./components/common/Icons.vue')['default']
    MessageToast: typeof import('./components/common/MessageToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./components/common/SliderCaptcha.vue')['default']
  }
}
