/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiPanel: typeof import('./../components/panels/AiPanel.vue')['default']
    HandPanel: typeof import('./../components/panels/HandPanel.vue')['default']
    LoginModal: typeof import('./../components/modals/LoginModal.vue')['default']
    MarkupPanel: typeof import('./../components/panels/MarkupPanel.vue')['default']
    PanelSection: typeof import('./../components/panels/PanelSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShapesPanel: typeof import('./../components/panels/ShapesPanel.vue')['default']
    TextPanel: typeof import('./../components/panels/TextPanel.vue')['default']
  }
}
