/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiPanel: typeof import('./../components/panels/AiPanel.vue')['default']
    CanvasArea: typeof import('./../components/editor/CanvasArea.vue')['default']
    ColorFloatPanel: typeof import('./../components/color/ColorFloatPanel.vue')['default']
    ColorPanel: typeof import('./../components/color/ColorPanel.vue')['default']
    CropPanel: typeof import('./../components/panels/CropPanel.vue')['default']
    DrawPanel: typeof import('./../components/panels/DrawPanel.vue')['default']
    EraserPanel: typeof import('./../components/panels/EraserPanel.vue')['default']
    ExitModal: typeof import('./../components/modals/ExitModal.vue')['default']
    HandPanel: typeof import('./../components/panels/HandPanel.vue')['default']
    HelpModal: typeof import('./../components/modals/HelpModal.vue')['default']
    ImagePanel: typeof import('./../components/panels/ImagePanel.vue')['default']
    LeftToolbar: typeof import('./../components/editor/LeftToolbar.vue')['default']
    LoginModal: typeof import('./../components/modals/LoginModal.vue')['default']
    MapModal: typeof import('./../components/modals/MapModal.vue')['default']
    MarkupPanel: typeof import('./../components/panels/MarkupPanel.vue')['default']
    PanelSection: typeof import('./../components/panels/PanelSection.vue')['default']
    RightPanel: typeof import('./../components/editor/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveModal: typeof import('./../components/modals/SaveModal.vue')['default']
    SelectPanel: typeof import('./../components/panels/SelectPanel.vue')['default']
    ShapesPanel: typeof import('./../components/panels/ShapesPanel.vue')['default']
    StyleFloatPanel: typeof import('./../components/brush/StyleFloatPanel.vue')['default']
    TextPanel: typeof import('./../components/panels/TextPanel.vue')['default']
    TopBar: typeof import('./../components/editor/TopBar.vue')['default']
  }
}
