/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./../components/modals/home/AboutModal.vue')['default']
    AiPanel: typeof import('./../components/panels/editor/AiPanel.vue')['default']
    AvatarHoverCard: typeof import('./../components/popovers/home/AvatarHoverCard.vue')['default']
    BioTooltip: typeof import('./../components/popovers/mine/BioTooltip.vue')['default']
    CanvasArea: typeof import('./../components/layouts/editor/CanvasArea.vue')['default']
    ColorFloatPanel: typeof import('./../components/panels/editor/ColorFloatPanel.vue')['default']
    ColorPanel: typeof import('./../components/panels/editor/ColorPanel.vue')['default']
    CropPanel: typeof import('./../components/panels/editor/CropPanel.vue')['default']
    DrawPanel: typeof import('./../components/panels/editor/DrawPanel.vue')['default']
    EraserPanel: typeof import('./../components/panels/editor/EraserPanel.vue')['default']
    ExitModal: typeof import('./../components/modals/editor/ExitModal.vue')['default']
    HandPanel: typeof import('./../components/panels/editor/HandPanel.vue')['default']
    HelpModal: typeof import('./../components/modals/editor/HelpModal.vue')['default']
    Icon: typeof import('./../components/common/Icon.vue')['default']
    ImagePanel: typeof import('./../components/panels/editor/ImagePanel.vue')['default']
    LeftToolbar: typeof import('./../components/layouts/editor/LeftToolbar.vue')['default']
    LoginModal: typeof import('./../components/modals/login/LoginModal.vue')['default']
    MapModal: typeof import('./../components/modals/editor/MapModal.vue')['default']
    MarkupPanel: typeof import('./../components/panels/editor/MarkupPanel.vue')['default']
    PanelSection: typeof import('./../components/panels/editor/PanelSection.vue')['default']
    PoseCard: typeof import('./../components/cards/home/PoseCard.vue')['default']
    RightPanel: typeof import('./../components/layouts/editor/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveModal: typeof import('./../components/modals/editor/SaveModal.vue')['default']
    SearchHero: typeof import('./../components/widgets/home/SearchHero.vue')['default']
    SelectPanel: typeof import('./../components/panels/editor/SelectPanel.vue')['default']
    SettingsModal: typeof import('./../components/modals/home/SettingsModal.vue')['default']
    ShapesPanel: typeof import('./../components/panels/editor/ShapesPanel.vue')['default']
    Sidebar: typeof import('./../components/layouts/home/Sidebar.vue')['default']
    SkeletonCard: typeof import('./../components/cards/home/SkeletonCard.vue')['default']
    StyleFloatPanel: typeof import('./../components/panels/editor/StyleFloatPanel.vue')['default']
    TextPanel: typeof import('./../components/panels/editor/TextPanel.vue')['default']
    TopBar: typeof import('./../components/layouts/editor/TopBar.vue')['default']
    TopNav: typeof import('./../components/layouts/home/TopNav.vue')['default']
  }
}
